version: 2

sources:
  - name: raw
    schema: main
    tables:
      - name: members
        description: Members of Congress (House + Senate)
      - name: bills
        description: Bills and resolutions
      - name: votes
        description: Roll call votes
      - name: member_votes
        description: Individual member voting positions
      - name: trades
        description: Stock trades by members of Congress
      - name: bill_cosponsors
        description: Bill cosponsor relationships
      - name: bill_actions
        description: Bill action timeline events
      - name: zip_districts
        description: Zip code to congressional district mappings
      - name: committees
        description: Congressional committees and subcommittees
      - name: committee_members
        description: Committee membership assignments
      - name: bill_subjects
        description: Legislative subject tags per bill
